[package]
name = "yaps-core"
version = "0.1.0"
edition = "2021"

[dependencies]
yaps-macros = { path = "../yaps-macros" }
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
yaps-serdes = { path = "../yaps-serdes" }
